chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:room_id>/message/', views.message, name='message'),
    path('create/', views.room_create, name='room'),
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('stocks/', include('stocks.urls')),
    path('chat/', include('chat.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

stocks/urls.py
from django.urls import path

from . import views

app_name = 'stocks'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('add/', views.add_ticker, name='add'),
    path('user/', views.create_user, name='user'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('portfolio/', views.PortfolioView.as_view(), name='portfolio'),
    path('addport/', views.add_portfolio, name='add_portfolio'),
    path('removeport/', views.remove_portfolio, name='remove_portfolio'),
    ]

stocks/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Stock(models.Model):
    symbol = models.CharField(max_length=10, unique=True)
    longName = models.CharField(max_length=100, default=None, blank=True, null=True)
    sector = models.CharField(max_length=100, default=None, blank=True, null=True)
    industry = models.CharField(max_length=100, default=None, blank=True, null=True)
    country = models.CharField(max_length=100, default=None, blank=True, null=True)
    currency = models.CharField(max_length=100, default=None, blank=True, null=True)
    added = models.DateTimeField()
    # users added stock
    portfolio = models.ManyToManyField(User)
    
    def __str__(self):
        return self.symbol

stocks/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.messages import get_messages
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.mixins import LoginRequiredMixin

from asgiref.sync import sync_to_async
import asyncio

from .models import Stock

import yfinance as yf

# Create your views here.

class DetailView(generic.DetailView):
    template_name = 'stocks/stockinfo.html'
    model = Stock

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c = Stock.objects.get(pk=self.kwargs['pk'])
        ticker = yf.Ticker(c.symbol)
        info = ticker.info
        prices = ticker.history(period='1mo')[['Close']]
        context['prices'] = prices.values.tolist()
        dates = ticker.history(period='1mo').index.tolist()
        datess = [int(x.strftime("%s%f"))/1000 for x in dates]
        context['dates'] = datess
        context['info'] = info
        if c.portfolio.filter(username=self.request.user).exists():
            context['userhas'] = True
        elif self.request.user.is_authenticated:
            context['userhas'] = False
        else:
            context['userhas'] = None            
        #print(prices)
        return context   
   
    def get_queryset(self):
        return Stock.objects

class IndexView(generic.ListView):
    template_name = 'stocks/index.html'
    context_object_name = 'stock_list'
    paginate_by = 7

    def get_messages(self):
        storage = get_messages(self.request)
        return storage

    '''
    def get_yf(self):
        list = []
        for s in Stock.objects.all():
            list.append(yf.Ticker(str(s)))
        return list
    '''
    
    def get_queryset(self):
        #l = self.get_yf()
        return Stock.objects.all().order_by('-added')

class PortfolioView(LoginRequiredMixin, generic.ListView):
    template_name = 'stocks/index.html'
    context_object_name = 'stock_list'
    paginate_by = 7

    def get_messages(self):
        storage = get_messages(self.request)
        return storage
    
    def get_queryset(self):
        return Stock.objects.filter(portfolio=self.request.user)
    
    
@sync_to_async
def get_ticker(symbol):
    y = yf.Ticker(symbol)
    #new_ticker=Stock(symbol='hi')    
    if 'sector' in y.info:
        #print(y.info)
        try:
            new_ticker = Stock(symbol=symbol.upper(), longName=y.info['longName'], sector=y.info['sector'], industry=y.info['industry'], country=y.info['country'], currency=y.info['currency'], added=timezone.now())
            new_ticker.save()
            print('saved')
            return (yf.Ticker(symbol), True)
        except Exception as e:
            a =Stock.objects.get(symbol=symbol)
            a.added = timezone.now()
            a.save()
            

            return (yf.Ticker(symbol), False)
    else:
        return (yf.Ticker(symbol), False)

async def add_ticker(request):
    ticker = request.POST['ticker'].upper()
    s = await( asyncio.create_task(get_ticker(ticker)))
    # 'sector' in ticker
    if 'sector' in s[0].info:
        if s[1] == False:            
            messages.info(request, ticker.upper() + ' is already in the list.')
            return HttpResponseRedirect(reverse('stocks:index',))
        else:
             messages.success(request, ticker.upper() + ' was added.')
             return HttpResponseRedirect(reverse('stocks:index')
    )
    messages.info(request, ticker.upper() + ' does not exist.')
    return HttpResponseRedirect(reverse('stocks:index'))
    
    ticker = request.POST['ticker'].upper()
    s = await asyncio.create_task(get_ticker(ticker))
    # 'sector' in ticker
    if 'sector' in s[0].info:
        if s[1] == False:
            
            messages.info(request, ticker.upper() + ' is already in the list.')
        return HttpResponseRedirect(reverse('stocks:index',))
    else:
        messages.info(request, ticker.upper() + ' does not exist.')
        return HttpResponseRedirect(reverse('stocks:index'))
    messages.success(request, ticker.upper() + ' was added.')
    return HttpResponseRedirect(reverse('stocks:index')
    )

def create_user(request):
    try:
        user = User.objects.create_user(username=request.POST['username'], password=request.POST['password'])        
        messages.info(request, 'Your account has been created')
        return HttpResponseRedirect(reverse('stocks:index'))
    except:
        messages.error(request, 'Try a different username')
        return HttpResponseRedirect(reverse('stocks:index'))

def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        auth_login(request, user)        
        return HttpResponseRedirect(reverse('stocks:index'))
    else:
        messages.error(request, 'Account not found')
        return HttpResponseRedirect(reverse('stocks:index'))

def logout(request):
    messages.info(request, "Logged out")
    print('hi')
    auth_logout(request)
    return HttpResponseRedirect(reverse('stocks:index'))

def add_portfolio(request):
    id = request.POST['id']
    try:
        s = Stock.objects.get(pk=id)
        s.portfolio.add(request.user)
        messages.success(request, 'Added to portfolio')
        return HttpResponseRedirect(reverse('stocks:detail', args=[id]))
    except Exception as e:
        print(e)
        messages.info(request, 'Already added to portfolio')
        return HttpResponseRedirect(reverse('stocks:detail', args=[id]))

def remove_portfolio(request):
    id = request.POST['id']
    try:
        s = Stock.objects.get(pk=id)
        s.portfolio.remove(request.user)
        messages.success(request, 'Removed from portfolio')
        return HttpResponseRedirect(reverse('stocks:detail', args=[id]))
    except Exception as e:
        print(e)
        messages.info(request, 'Already removed from portfolio')
        return HttpResponseRedirect(reverse('stocks:detail', args=[id]))

stocks/templates/stocks/index.html
<!doctype html>
{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'stocks:index' %}">Stock Market</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">    

    {% if user.is_authenticated %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class='nav-link' href='{% url "stocks:portfolio" %}'>My portfolio<span class="sr-only">(current)</span></a>
      </li>
    <form action='{% url "stocks:logout" %}' method='post'>
      {% csrf_token %}
      <input class='btn btn-danger' type='submit' value='Logout'>
    </form>
    {% else %}
    <div class='container'>
  <div class='row mr-auto'>
    <div class='col-sm'>
      <form action='{% url "stocks:user" %}' method='post'>
      {% csrf_token %}
      <input class='form-control' required placeholder='username' type='text' name='username'>
      <input class='form-control' required placeholder='password' type='password' name='password'>
      <input class='btn btn-primary' type='submit' value='Create an account'>
      </form>
    </div>

    <div class='col-sm'>
      <form action='{% url "stocks:login" %}' method='post'>
	{% csrf_token %}
	<div class='col-sm'>
	  <input class='form-control' required placeholder='username' type='text' name='username'>
	  <input class='form-control' required placeholder='password' type='password' name='password'>
	  <input class='btn btn-secondary' type='submit' value='Login'>
	</div>
      </form>
    </div>
  </div>
    </div>
    {% endif %}
  </div>
</nav>

<div class='container'>
{% if user.is_authenticated %}
<div class="alert alert-success" role="alert">
  <h5>Welcome, {{ user }}</h5>
</div>
{% endif %}

{% if request.path == '/stocks/portfolio/' %}
<h5>Portfolio</h5>
{% else %}
<form action='{% url "stocks:add" %}' method="post">
  {% csrf_token %}
  <div class='input-group'>
  <input class='form-control' required placeholder="Search company ticker" type="text" name="ticker">
  <input class='btn btn-info' type="submit" value="Search">
  </div>
</form>
{% endif %}

{% if messages %}
{% for message in messages %}
<div role='alert' class='alert alert-primary'>{{ message }}</div>
{% endfor %}
{% endif %}

{% if stock_list %}
<table class="table table-primary">
<thead>
  <tr>
    <th scope="col">Symbol</th>
    <th scope="col">Company</th>
    <th scope="col">Sector</th>
    <th scope="col">Industry</th>
    <th scope="col">Country</th>
    <th scope="col">Currency</th>
  </tr>
</thead>
{% for stock in stock_list %}
<tr class="table-light">
  <td class="table-primary">
    <a href='{% url 'stocks:detail' stock.id %}'>
      {{ stock }}
    </a>
  </td>
  <td class="table-primary">
    {{ stock.longName }}
  </td>
  <td class="table-primary">
    {{ stock.sector }}
  </td>
  <td class="table-primary">
    {{ stock.industry }}
  </td>
  <td class="table-primary">
    {{ stock.country }}
  </td>
  <td class="table-primary">
    {{ stock.currency }}
  </td>
</tr>
{% endfor %}
</table>
{% endif %}

{% if is_paginated %}
<div class='mb-5'>
{% for page in paginator.page_range  %}
<a class='btn btn-outline-primary' href="?page={{ page }}">{{ page }}</a>
{% endfor %}
</div>
{% endif %}

</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

stocks/templates/stocks/stockinfo.html
<!doctype html>
{% load static %}
{% load humanize %}
{{ my_num|intcomma }}

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'stocks:index' %}">Stock Market</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">    

    {% if user.is_authenticated %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class='nav-link' href='{% url "stocks:portfolio" %}'>My portfolio<span class="sr-only">(current)</span></a>
      </li>
    <form action='{% url "stocks:logout" %}' method='post'>
      {% csrf_token %}
      <input class='btn btn-danger' type='submit' value='Logout'>
    </form>
    {% else %}
    <div class='container'>
  <div class='row mr-auto'>
    <div class='col-sm'>
      <form action='{% url "stocks:user" %}' method='post'>
      {% csrf_token %}
      <input class='form-control' required placeholder='username' type='text' name='username'>
      <input class='form-control' required placeholder='password' type='password' name='password'>
      <input class='btn btn-primary' type='submit' value='Create an account'>
      </form>
    </div>

    <div class='col-sm'>
      <form action='{% url "stocks:login" %}' method='post'>
	{% csrf_token %}
	<div class='col-sm'>
	  <input class='form-control' required placeholder='username' type='text' name='username'>
	  <input class='form-control' required placeholder='password' type='password' name='password'>
	  <input class='btn btn-secondary' type='submit' value='Login'>
	</div>
      </form>
    </div>
  </div>
    </div>
    {% endif %}
  </div>
</nav>


<div class='container'> 


{% if userhas == False %}
<form action='{% url "stocks:add_portfolio" %}' method='post'>
  {% csrf_token %}
  <input hidden type='text' value='{{ stock }}' name='stock'>
  <input hidden type='text' value='{{ stock.id }}' name='id'>
  <input class='btn btn-success' type='submit' value='Add to portfolio'>
</form>
{% elif userhas == True %}
<form action='{% url "stocks:remove_portfolio" %}' method='post'>
  {% csrf_token %}
  <input hidden type='text' value='{{ stock }}' name='stock'>
  <input hidden type='text' value='{{ stock.id }}' name='id'>
  <input class='btn btn-warning' type='submit' value='Remove from portfolio'>
</form>
{% endif %}

{% if messages %}
{% for message in messages %}
<div class='alert alert-info'>{{ message }}</div>
{% endfor %}
{% endif %}

<div class='d-flex p-2 bd-highlight'>
  <div>
    <table class='table table-striped'>
      <tbody>
	<tr>
	  <td>Name</td>
	  <td>{{stock.longName}}</td>
	</tr>
	<tr>
	  <td>Symbol</td>
	  <td>{{stock}}</td>
	</tr>
      </tbody>
    </table>
  </div>
</div>
<div class='d-flex p-2 bd-highlight'>
  <div>
    <table class="table table-striped">
      <tbody>
	<tr>	
	  <td>Bid</td>
	  <td>{{ info.bid|intcomma }}</td>
	<tr>
	  <td>Ask</td>
	  <td> {{ info.ask|intcomma }}</td>
	</tr>
	<tr>
	  <td>Previous close </td>
	  <td>{{ info.previousClose|intcomma }}</td>
	</tr>
	<tr>
	  <td>Open</td>
	  <td>{{ info.open|intcomma }}</td>
	</tr>
      </tbody>
    </table>
  </div>
  <div>
    <table class="table table-striped">
      <tbody>
	<tr>	
	  <td>Day's range</td>
	  <td>{{ info.dayLow|intcomma }} - {{ info.dayHigh|intcomma }}</td>
	<tr>
	  <td>Market cap</td>
	  <td>{{ info.marketCap|intcomma }}</td>
	</tr>
	<tr>
	  <td>Volume</td>
	  <td>{{ info.volume|intcomma }}</td>
	</tr>
	<tr>
	  <td>Close</td>
	  <td id='close'></td>
	</tr>
      </tbody>
    </table>
  </div>
</div>

<p hidden id='dates'>{{ prices.Open.keys }}</p>

<canvas id='chart' width='200' height='100'></canvas>

</div>

<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js'>
  </script>
<script>
  var p = {{prices}}.map(x=>x[0].toFixed(2))
  var d = {{dates}}.map(x=>new Date(x).toDateString())
  
  close = document.getElementById('close')
  close.innerText = p.slice(-1) + ' on ' + d.slice(-1)


  var ctx = document.getElementById('chart');
  var myChart = new Chart(ctx, {
    type: 'line',
    options: {
	elements: {
	    point: {
		radius: 3
	    }
	},
	tooltips: {
	    intersect: false
	}
    },
    data: {
        labels: d,
        datasets: [{
            label: 'Close Price in'+' {{stock.currency}}',
          data: p,            
            borderWidth: 1
        }]
    }
});  
</script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>