chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:room_id>/message/', views.message, name='message'),
    path('create/', views.room_create, name='room'),
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('stocks/', include('stocks.urls')),
    path('chat/', include('chat.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

chat/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Room(models.Model):
    room_name = models.CharField(max_length=100, null=False, blank=False)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.room_name
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.boolean = True

class Message(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    username = models.CharField(max_length=30, default='Anonymous')
    message_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    def __str__(self):
        return self.message_text

chat/views.py
from django.shortcuts import render
from django.views import generic
from django.utils import timezone
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect

from .models import Room, Message

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'chat/index.html'
    context_object_name = 'chat_room_list'
    
    def get_queryset(self):
        return Room.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')

class DetailView(generic.DetailView):
    model = Room
    template_name = 'chat/detail.html'
    def get_queryset(self):
        return Room.objects

def room_create(request):
    rm = request.POST['room']
    if len(rm.replace(' ', '')) == 0:
        return HttpResponseRedirect(reverse('chat:index'))
    room = Room(room_name=request.POST['room'], pub_date=timezone.now())
    room.save()
    return HttpResponseRedirect(reverse('chat:index'))

def message(request, room_id):
    room = get_object_or_404(Room, pk=room_id)
    if len(request.POST['message'].replace(' ','')) == 0:
        return HttpResponseRedirect(reverse('chat:detail',args=(room_id,)))
    m = Message(message_text=request.POST['message'], username=request.POST['username'], room=room, pub_date=timezone.now())
    m.save()
    #print(request.POST)
    return HttpResponseRedirect(reverse('chat:detail', args=(room_id,)))

chat/templates/chat/detail.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

<div class="container pt-3">
<h3>Chat: {{ room.room_name }}</h3>

<div class="container pt-3 h-50 overflow-auto" id='chat-log'>
  <div style='display:none' id="msg" class="flex-row pt-2">
    <div id='username' class="col fw-bold">{{ message.username }}
      <span class='fw-lighter text-muted'>
	<small id='date'>{{message.pub_date}}</small>
      </span>
    </div>
    <div id='message' class="col">
    {{ message.message_text }}
    </div>  
  </div>
  {% for message in room.message_set.all %}
  <div id="msg" class="flex-row pt-2">
    <div id='username' class="col fw-bold">{{ message.username }}
      <span class='fw-lighter text-muted'>
	<small id='date'>{{message.pub_date}}</small>
      </span>
    </div>
    <div id='message' class="col">
    {{ message.message_text }}
    </div>  
  </div>
  {% endfor %}
  <div id='chat-bot'></div>
</div>
<!--
<form action="{% url 'chat:message' room.id %}" method="post">
  {% csrf_token %}
  <input type="text" name="username" value="">
  <label for="username">Name</label><br>
  <input type="text" name="message" value="">
  <label for="message">Your message</label><br>
  <input type="submit" value="Message">
</form>
-->
{{ room.id|json_script:'room-name' }}
<div class="container">  
  <div class="row pt-3">
    <div class="col-sm">
      <input placeholder="User" id="username-input" type="text" name="user" size="20" class="form-control">
    </div>
  <div class="col-sm">
    <input placeholder="Message" id="chat-message-input" type="text" name="message" class="form-control" required>    
  </div>
  <div class="col-sm">
    <input id="chat-message-submit" type="button" value="Send" class="btn btn-primary">
    <a href="{% url 'chat:index'  %}" class="btn btn-danger">Leave</a>
  </div>
</div>

  <script>
    function scroll() {
	//let view = document.getElementById('chat-bot')
	//view.scrollIntoView(true);
	document.getElementById("chat-log").scrollTop += document.getElementById('chat-log').scrollHeight;

	//console.log(view)
    }
    scroll()

    //setInterval(function(){ scroll(); }, 1000);
    
  const roomName = JSON.parse(document.getElementById('room-name').textContent);

  const chatSocket = new WebSocket(
      'wss://'
	  + window.location.host
	  + '/ws/chat/'
	  + roomName
	  + '/'
  );

  chatSocket.onmessage = function(e) {
      const data = JSON.parse(e.data)
      const original = document.getElementById('msg')
      let m = original.cloneNode(true)
      m.querySelector('#username').firstChild.nodeValue = data.username
      m.querySelector('#date').textContent = new Date(data.date).toLocaleTimeString().toLowerCase().replace('am','a.m.').replace('pm','p.m.')
      setTimeout(function(){ scroll(); }, 100);
     

      

      m.querySelector('#message').textContent = data.message
      m.style.display = 'block';
      console.log(data.username)
      console.log(m.querySelector('#username'))
      document.querySelector('#chat-log').insertBefore(m, document.getElementById('chat-bot'));
  }
  chatSocket.onclose = function(e) {
      console.error('chat socket closed unexpectedly')
  }

  document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
	 document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
	    if (messageInputDom.value == '') {
		return;
	    }
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
		'username': document.querySelector('#username-input').value
            }));
            messageInputDom.value = '';
        };

</script>

chat/templates/chat/index.html
<!doctype html>
{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="{% static 'chat/style.css' %}">

<div class="container pt-4">
  <h3>Chat rooms</h3>
  <div>
<form action="{% url 'chat:room' %}" method="post">
  {% csrf_token %}
  <label for="room" class="form-label">Create a room</label>
  <input required type="text" name="room">
  <input type="submit" class="btn btn-primary" value='Submit'>
</form>
</div>

{% if chat_room_list %}
<div class="container pt-2">
  {% for room in chat_room_list %}
  <div class="flex-row pt-2">
    <div class="flex-column align-items-center">
    <a href="{% url 'chat:detail' room.id %}">{{ room.room_name }}</a>
    </div>
    <div class="flex-column col">
      <p>{{ room.pub_date }}</p>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<p>No chat rooms.</p>
{% endif %}

</div>